### ISSUE TITLE
Using proxy path

### ISSUE THREAD

**Issue by mikesmichael** [insidewhy/rxjs-websockets#145]
Hi

Is it possible to use a relative path with a proxy rewrite?

I got message:
`
DOMException: Failed to construct 'WebSocket': The URL '/apis/websockets/route?param=value' is invalid.`

Thanks

**Comment by insidewhy** [comment]
This is a question about the `WebSocket` API, rather than `rxjs-websockets`. But no, I don't think it's possible, since you need the `ws://` or `wss://` prefix for websockets.
