### ISSUE TITLE
Socket disconnection status not propagating to parent component 

### ISSUE THREAD

**Issue by gharia** [insidewhy/rxjs-websockets#158]
I have been using rxjs-websockets **v8.0.1** in react (typescript) as a separate class called `Socket`. And this `Socket` class is being used in multiple components. Following is my way to subscribe to connection status. 2 is the default (when component initializes), 1 is connected and 0 is disconnected.

```
inputStream$: QueueingSubject<string> = new QueueingSubject<string>();
messages$!: Observable<string>;
connectionStatus$: BehaviorSubject<number> = new BehaviorSubject(2);
messagesSubscription: Subscription | null = null;

connect(url: string) {
        
    const socket$ = makeWebSocketObservable(url);
	
	this.messages$ = socket$.pipe(
		  switchMap((getResponses: GetWebSocketResponses<string>) => {
			this.connectionStatus$.next(1);
			return getResponses(this.inputStream$);
		  }),
		  retryWhen(errors => {
			console.log("disconnected - retryWhen block");
			this.connectionStatus$.next(0);
			return errors.pipe(
					filter(err => !equals(err.message, normalClosureMessage)),
					delay(1000));
		  }),
		  share(),
	  );
	  
	  
	  this.messagesSubscription = this.messages$!.subscribe(
		  _ => {
			return;
		  },
		  (error: Error) => {
			const { message } = error;
			  this.connectionStatus$.next(0);
			  console.log('socket was disconnected due to error:', message);        
		  },
		  () => {
			// The clean termination only happens in response to the last
			// subscription to the observable being unsubscribed, any
			// other closure is considered an error.
			this.connectionStatus$.next(0);
			console.log('the connection was closed in response to the user')
		  },
	  )
  }
  
```
The parent component is subscribing to `connectionStatus$` and accordingly behave. For testing I am closing WebSocket connection from server by restarting the server. But after the connection, only for the first disconnection event, I see `disconnected - retryWhen block` and parent component get that disconnection event. After that, if there is a disconnection, I don't see that log and parent component does not get the disconnection event/status. 

Also, when I deliberately turn off network adapter, I see the WebSocket connection gets closed and retries get started which keeps failing with the below logs. 
```
glue.js:30 WebSocket connection to 'wss://mydomain.com/glue/ws' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
o.open @ glue.js:30
(anonymous) @ glue.js:148
d @ raven.min.js:2
raven.js:80 ["the websocket closed the connection with an error."]

```
Note that the socket does get reconnected in every case, whether I restart the server or on/off wifi adapter. So reconnection is not the issue. But not identifying and propagating each and every disconnection event is the issue. Also, after reconnected, I get the event in the parent component, which I think due to the first message response (see switchMap in the above code).

Maybe I am missing something here. But what is the correct way to subscribe to connection state change?

Thanks

**Comment by gharia** [comment]
I think the solution is to implement ping/pong (which we already have) and observe the last ping time. Add a specific timeout on ping, say for e.g. 1 min. If the last received ping/pong has exceeded more than a minute than disconnect unsubscribing all subscriptions and reconnect.

Closing this as this needs to be handled at the application/protocol level specific to one's app. In case anyone has a better idea, please share.

**Comment by insidewhy** [comment]
You won't get the error event in the subscription when you use `retryWhen`.

**Comment by insidewhy** [comment]
Other than that being redundant, your method of managing the connection status observable looks good.

**Comment by insidewhy** [comment]
I've found that reconnection periods below 3 seconds cause chrome to start blocking the reconnection attempts. This isn't a bug in the library as I've seen it using only the WebSocket API. This might be why you're seeing rxjs-websockets fail to reconnect in certain circumstances.
