### ISSUE TITLE
RxJS 7.x compat

### ISSUE THREAD

**Issue by davidzwa** [insidewhy/rxjs-websockets#188]
https://www.npmjs.com/package/rxjs
Versions show that RxJS 7 has been released for 3 months. This library is now limited to 6.6.x which holds me from using it - not a big issue but my thought was if I think this maybe someone else does when they do a fresh rxjs install using NPM/yarn.
Would be lovely to see this wonderful implementation be suitable for RxJS 7+. It is worth your past efforts to give it a shot soon and keep this library fresh and state of the art. Keep up the good work 🚀

**Comment by insidewhy** [comment]
I'll update it soon

**Comment by insidewhy** [comment]
Released rxjs-websockets 9.0.0 now with support for rxjs 7, thanks for your report!
